- hosts: all  # Spécifie les hôtes sur lesquels ces tâches doivent être exécutées
  gather_facts: false  # Indique à Ansible de ne pas collecter les faits (informations système) des hôtes
  become: true  # Indique à Ansible de devenir superutilisateur (root) lors de l'exécution des tâches
  vars_files:
    - var.yml
  roles:
    - docker
    - network
    - database
    - app
    - proxy
    - front