
# Install Docker
  - name: Install device-mapper-persistent-data  # Nom de la tâche
    yum:  # Utilisation du module yum pour gérer les packages
      name: device-mapper-persistent-data  # Nom du package à installer
      state: latest  # Spécifie d'installer la dernière version disponible

  - name: Install lvm2  # Nom de la tâche
    yum:  # Utilisation du module yum pour gérer les packages
      name: lvm2  # Nom du package à installer
      state: latest  # Spécifie d'installer la dernière version disponible

  - name: add repo docker  # Nom de la tâche
    command:  # Utilisation du module command pour exécuter une commande shell
      cmd: sudo yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo  # Commande à exécuter pour ajouter le dépôt Docker

  - name: Install Docker  # Nom de la tâche
    yum:  # Utilisation du module yum pour gérer les packages
      name: docker-ce  # Nom du package Docker à installer
      state: present  # Spécifie que le package doit être présent (installé)

  - name: Install python3  # Nom de la tâche
    yum:  # Utilisation du module yum pour gérer les packages
      name: python3  # Nom du package à installer
      state: present  # Spécifie que le package doit être présent (installé)

  - name: Install docker with Python 3  # Nom de la tâche
    pip:  # Utilisation du module pip pour gérer les packages Python
      name: docker  # Nom du package Python à installer
      executable: pip3  # Spécifie l'exécutable pip3 pour installer le package
    vars:  # Définition de variables spécifiques à cette tâche
      ansible_python_interpreter: /usr/bin/python3  # Spécifie l'interpréteur Python à utiliser pour cette tâche

  - name: Make sure Docker is running  # Nom de la tâche
    service:  # Utilisation du module service pour gérer les services
      name: docker  # Nom du service à gérer (Docker)
      state: started  # Spécifie que le service doit être démarré
    tags: docker  # Associe cette tâche au tag "docker" pour une exécution sélective avec des tags