  - name: Run front
    docker_container:
      name: front
      image: mathismrg/front:latest
      networks:
        - name: app_network
    vars:
      ansible_python_interpreter: /usr/bin/python3
