  - name: Run backend
    docker_container:
      name: tp1-backend
      image: mathismrg/tp1-backend:latest
      networks:
        - name: app_network
      env:
        DB_URL: "{{ DB_URL }}"
        DB_username: "{{ DB_username }}"
        DB_password: "{{ DB_password }}"
    vars:
      ansible_python_interpreter: /usr/bin/python3
