FROM postgres:14.1-alpine

# variable d'environnement ecraser par le .env
ENV POSTGRES_DB=db \
   POSTGRES_USER=usr \
   POSTGRES_PASSWORD=pwd

COPY DB_scripts/01-CreateScheme.sql /docker-entrypoint-initdb.d
COPY DB_scripts/02-InsertData.sql /docker-entrypoint-initdb.d

EXPOSE 5432