# Choix de l'image de base, ici une postgres qui tourne avec un OS Alpine
FROM postgres:14.1-alpine

# variable d'environnement ecraser par le .env
ENV POSTGRES_DB=db \
   POSTGRES_USER=usr \
   POSTGRES_PASSWORD=pwd

# Copy des scripts d'initialisation de base de données
COPY DB_scripts/01-CreateScheme.sql /docker-entrypoint-initdb.d
COPY DB_scripts/02-InsertData.sql /docker-entrypoint-initdb.d

# Port exposé
EXPOSE 5432