# Marque le début de la définition de l'inventaire Ansible
all:
  # Définition des variables globales pour tous les hôtes
  vars:
    # Spécifie le chemin de la clé privée SSH
    ansible_user: centos
    # Spécifie le chemin de la clé privée SSH
    # ansible_ssh_private_key_file: /mnt/home/users/mathis.malek/desktop/DevOps/id_rsa
    # POSTGRES_DB: db
    # POSTGRES_USER: usr
    # POSTGRES_PASSWORD: pwd
    # DB_URL: jdbc:postgresql://tp1-database:5432/db
    # DB_username: usr
    # DB_password: pwd
  # Début de la définition des groupes d'hôtes
  children:
    # Définit un groupe d'hôtes nommé "prod"
    prod:
      # Spécifie les hôtes inclus dans le groupe "prod"
      hosts: centos@mathis.malek.takima.cloud
