# Marque le début de la définition de l'inventaire Ansible
all:
  # Définition des variables globales pour tous les hôtes
  vars:
    # Spécifie le chemin de la clé privée SSH
    ansible_user: centos
  # Début de la définition des groupes d'hôtes
  children:
    # Définit un groupe d'hôtes nommé "prod"
    prod:
      # Spécifie les hôtes inclus dans le groupe "prod"
      hosts: centos@mathis.malek.takima.cloud
