version: "3.7"

services:
  backend:
    image: mathismrg/tp1-backend:latest
    networks:
      - app-network
    env_file: .env
    depends_on:
      - database
    container_name: tp1-backend

  database:
    image: mathismrg/tp1-database:latest
    networks:
      - app-network
    volumes:
      - dataDir:/var/lib/postgresql/data
    env_file: .env
    container_name: postgresTP1

  httpd:
    image: mathismrg/tp1-httpd:latest
    ports:
      - "8081:80"
    networks:
      - app-network
    depends_on:
      - backend
    container_name: httpdTP1
  
  front:
    build:
      context: ../front
    networks:
      - app-network
    depends_on:
      - backend
    container_name: front

  adminer:
    image: adminer
    restart: always
    networks:
      - app-network
    ports:
      - 8090:8080

networks:
  app-network:

volumes:
  dataDir: