  - name: Run HTTPD
    docker_container:
      name: tp1-httpd
      image: mathismrg/tp1-httpd:latest
      networks:
        - name: app_network
      exposed_ports:
        - "80:80"
    vars:
      ansible_python_interpreter: /usr/bin/python3
