# Build
FROM maven:3.8.6-amazoncorretto-17 AS javaTP1
ENV MYAPP_HOME /opt/myapp
WORKDIR $MYAPP_HOME
COPY ./simpleapi/simpleapi/pom.xml .
COPY ./simpleapi/simpleapi/src ./src
RUN mvn package -DskipTests

# Run
FROM amazoncorretto:17
ENV MYAPP_HOME /opt/myapp
WORKDIR $MYAPP_HOME
COPY --from=javaTP1 $MYAPP_HOME/target/*.jar $MYAPP_HOME/myapp.jar

ENTRYPOINT java -jar myapp.jar