name: Deploy with Ansible
on:
  workflow_run:
    workflows: ["build-and-push-docker"]
    branches: [main]
    types:
      - completed

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-22.04
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Setting up SSH key and vault password
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/private_key.pem
          chmod 600 ~/private_key.pem
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          ssh-keyscan -t rsa,dsa,ecdsa,ed25519 mathis.malek.takima.cloud >> ~/.ssh/known_hosts

      - name: Setting up Vault password
        run: |
          echo "${{ secrets.VAULT_PASSWORD }}" > ~/vault_pass.pem
          chmod 600 ~/vault_pass.pem

      - name: Run Ansible Playbook
        run: |
          sudo apt update
          sudo apt install -y ansible
          cd ./TP3/ansible
          ansible-playbook -i ./inventories/setup.yml ./playbook.yml --private-key=~/private_key.pem --vault-password-file=~/vault_pass.pem