name: build-and-push-docker
on:
  #to begin you want to launch this job in main and develop
  workflow_run:
    branches:
      - "main"
    workflows : ["test-backend"]
    types:
      - completed

  # define job to build and publish docker image
jobs:
  build-and-push-docker-image:
    # needs: test-backend
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-22.04
    if: ${{ github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success' }}

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_LOGIN_USERNAME_TAG }} -p ${{ secrets.DOCKER_LOGIN_PASSWORD }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./TP1/java
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKER_LOGIN_USERNAME_TAG}}/tp1-backend:latest
          push: ${{ github.ref == 'refs/heads/main' }}
      
      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./TP1/httpd
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKER_LOGIN_USERNAME_TAG}}/tp1-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./TP1/db
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKER_LOGIN_USERNAME_TAG}}/tp1-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}
